"""
Energy Database Module
This module handles SQLite operations for energy statistics.
"""
import json
import os
import sqlite3
import pandas as pd

class EnergyDatabase:
    """
       EnergyDatabase is responsible for storing energy-related data
       into an SQLite database in a safe and repeatable way.
    """
    def __init__(self, db_name="energy_data.db"):
        """
        Initializes the database name and prepares the database.
        """
        self.db_name = db_name
        self.setup_db()

    def setup_db(self):
        """
        Prepares the SQLite database.
        Creates the table and index if they do not already exist.
        """
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()

        cursor.execute('''
                       CREATE TABLE IF NOT EXISTS fuel_energy_stats
                       (
                           id                      INTEGER PRIMARY KEY AUTOINCREMENT,
                           date                    TEXT,
                           hour                    TEXT,
                           city                    TEXT,
                           solar_radiation         REAL,
                           wind_speed              REAL,
                           solar_energy_real       REAL,
                           solar_energy_calculated REAL,
                           wind_energy_real        REAL,
                           wind_energy_calculated  REAL,
                           total_energy            REAL
                       )
                       ''')

        cursor.execute('CREATE INDEX IF NOT EXISTS idx_time ON fuel_energy_stats (date, hour)')
        conn.commit()
        conn.close()
        print(f"Database setup successful: {self.db_name} is ready.")

    def store_json_to_sql(self, json_file_path):
        """
        Reads a JSON file generated by Scrapy and stores
        its contents into the SQLite database.
        """
        if not os.path.exists(json_file_path):
            print(f"Error: {json_file_path} not found!")
            return

        try:
            with open(json_file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            if not isinstance(data, list):
                print("Error: JSON root must be a list.")
                return
            df = pd.DataFrame(data)
            allowed_columns = {
                "Date", "Hour", "City",
                "Solar Radiation", "Wind Speed",
                "Solar Energy", "Wind Energy", "Total Energy"
            }
            df = df[[c for c in df.columns if c in allowed_columns]]
            name_mapping = {
                "Date": "date",
                "Hour": "hour",
                "Total Energy": "total_energy",
                "Solar Energy": "solar_energy_real",
                "Wind Energy": "wind_energy_real"
            }
            df = df.rename(columns=name_mapping)
            all_columns = ['date', 'hour', 'city', 'solar_radiation', 'wind_speed',
                           'solar_energy_real', 'solar_energy_calculated',
                           'wind_energy_real', 'wind_energy_calculated', 'total_energy']
            for col in all_columns:
                if col not in df.columns:
                    df[col] = None

            df = df[all_columns]
            conn = sqlite3.connect(self.db_name)
            df.to_sql('fuel_energy_stats', conn, if_exists='append', index=False)
            conn.commit()
            conn.close()
            print(f"Success {len(df)} rows inserted into the database.")
        except json.JSONDecodeError as e:
            print(f"Invalid JSON format: {e}")
        except sqlite3.DatabaseError as e:
            print(f"Database error: {e}")
        except Exception as e:  # pylint: disable=broad-exception-caught
            print(f"Data storage error: {e}")
if __name__ == "__main__":
    # Executes the data import process when the script is run directly
    db = EnergyDatabase()
    db.store_json_to_sql('energy_data.json')
